import type { PublicUser } from '../../types/user.js';
import { AppError } from '../../utils/httpError.js';
import { requireCurrentUser,requireObject,requireString,requireUuid } from '../../utils/moduleValidation.js';
import { notificationService } from '../../services/notification.service.js';
import { emitToConversation } from '../../realtime/realtime.events.js';
import { supportRepository } from './support.repository.js';
import type { SupportActor } from './support.types.js';

const sends=new Map<string,number>();
function actor(user?:PublicUser):SupportActor{const current=requireCurrentUser(user);if(current.role!=='student'&&current.role!=='mentor')throw new AppError(403,'Private support conversations are available to students and mentors only.',[],'SUPPORT_FORBIDDEN');return{id:current.id,role:current.role,fullName:current.fullName}}
async function authorized(id:string,user?:PublicUser){requireUuid(id);const current=actor(user);const conversation=await supportRepository.find(id,current);if(!conversation)throw new AppError(404,'Support conversation not found.',[],'SUPPORT_CONVERSATION_NOT_FOUND');return{current,conversation}}
function messagePayload(row:Record<string,unknown>,current:SupportActor,isAnonymous:boolean){return{id:String(row.id),conversationId:String(row.conversation_id),sender:{role:current.role,displayName:current.role==='student'&&isAnonymous?'Anonymous Student':current.role==='mentor'?'CampusCare Mentor':current.fullName},message:String(row.message),createdAt:row.created_at}}

export const supportService={
  list:(user?:PublicUser)=>supportRepository.list(actor(user)),
  get:async(id:string,user?:PublicUser)=>{const access=await authorized(id,user);return{conversation:access.conversation,messages:await supportRepository.messages(id,access.current)}},
  sendByHelpRequest:async(helpRequestId:string,payload:unknown,user?:PublicUser)=>{requireUuid(helpRequestId);const current=actor(user);const conversation=await supportRepository.findByHelpRequest(helpRequestId,current);if(!conversation)throw new AppError(404,'Support conversation not found.',[],'SUPPORT_CONVERSATION_NOT_FOUND');return supportService.send(conversation.id,payload,user)},
  join:async(id:string,user?:PublicUser)=>{const access=await authorized(id,user);if(access.current.role==='mentor'&&!access.conversation.mentorUserId){const claimed=await supportRepository.claim(id,access.current.id);if(!claimed)throw new AppError(409,'This support conversation has already been assigned.',[],'SUPPORT_ALREADY_ASSIGNED');const participants=await supportRepository.participants(id);if(participants?.student_user_id)await notificationService.create({userId:String(participants.student_user_id),type:'help_request',title:'Mentor support started',message:'A mentor is now supporting your Silent Help request.',link:`/silent-help?request=${access.conversation.helpRequestId}`});return{...access.conversation,mentorUserId:access.current.id}}return access.conversation},
  send:async(id:string,payload:unknown,user?:PublicUser)=>{const access=await authorized(id,user);if(access.conversation.status==='closed')throw new AppError(409,'This support conversation is closed.',[],'SUPPORT_CONVERSATION_CLOSED');const data=requireObject(payload);const message=requireString(data.message,'message',2000);const clientMessageId=data.clientMessageId===undefined?null:requireUuid(String(data.clientMessageId));if(access.current.role==='mentor'&&!access.conversation.mentorUserId)await supportService.join(id,user);const now=Date.now();if(now-(sends.get(access.current.id)??0)<750)throw new AppError(429,'Please wait before sending another message.',[],'SUPPORT_MESSAGE_RATE_LIMITED');sends.set(access.current.id,now);const saved=await supportRepository.addMessage(id,access.current,message,clientMessageId);const outgoing=messagePayload(saved,access.current,access.conversation.isAnonymous);if(!saved.inserted)return outgoing;emitToConversation(id,'support:message:new',outgoing);const participants=await supportRepository.participants(id);const recipient=access.current.role==='student'?participants?.mentor_user_id:participants?.student_user_id;if(recipient)await notificationService.create({userId:String(recipient),type:'reply',title:access.current.role==='mentor'?'New mentor reply':'New support message',message:access.current.role==='mentor'?'A mentor replied to your Silent Help request.':`${access.conversation.isAnonymous?'Anonymous Student':'A student'} sent a support message.`,link:`/silent-help?request=${access.conversation.helpRequestId}`});return outgoing},
  markRead:async(id:string,user?:PublicUser)=>{const access=await authorized(id,user);await supportRepository.markRead(id,access.current);return{read:true}},
  close:async(id:string,user?:PublicUser)=>{const access=await authorized(id,user);if(access.current.role!=='mentor'||access.conversation.mentorUserId!==access.current.id)throw new AppError(403,'Only the assigned mentor can close this conversation.',[],'SUPPORT_CLOSE_FORBIDDEN');const closed=await supportRepository.close(id,access.current.id);emitToConversation(id,'support:status-changed',{conversationId:id,status:'closed'});const participants=await supportRepository.participants(id);if(participants?.student_user_id)await notificationService.create({userId:String(participants.student_user_id),type:'help_request',title:'Support request resolved',message:'Your Silent Help request was resolved.',link:`/silent-help?request=${access.conversation.helpRequestId}`});return closed},
  authorize:authorized
};
