import assert from 'node:assert/strict';
import test from 'node:test';
import type { PublicUser } from '../../types/user.js';
import { mapSupportMessage, supportRepository } from './support.repository.js';
import { supportService } from './support.service.js';
import { notificationService } from '../../services/notification.service.js';

const user=(role:'student'|'mentor',id:string):PublicUser=>({id,role,fullName:role==='student'?'Private Student':'Test Mentor',email:`${role}@example.com`,createdAt:new Date(),updatedAt:new Date()});
const student=user('student','10000000-0000-4000-8000-000000000001'),other=user('student','10000000-0000-4000-8000-000000000002'),mentor=user('mentor','10000000-0000-4000-8000-000000000003');
const conversation={id:'20000000-0000-4000-8000-000000000001',helpRequestId:'30000000-0000-4000-8000-000000000001',title:'Support',category:'subject',isAnonymous:true,status:'open',mentorUserId:null,participantLabel:'Anonymous Student',unreadCount:0,createdAt:new Date(),updatedAt:new Date(),closedAt:null};

test('anonymous mentor payload strips student identity',()=>{const mapped=mapSupportMessage({id:'1',conversation_id:'2',sender_role:'student',message:'Help',created_at:new Date(),is_anonymous:true,full_name:'Private Student'},{id:mentor.id,role:'mentor',fullName:mentor.fullName});assert.equal(mapped.sender.displayName,'Anonymous Student');assert.equal(JSON.stringify(mapped).includes('Private Student'),false)});
test('owning student sees mentor messages in anonymous history',()=>{const mapped=mapSupportMessage({id:'1',conversation_id:conversation.id,sender_role:'mentor',message:'Mentor guidance',created_at:new Date(),is_anonymous:true,full_name:'Mentor Name'},{id:student.id,role:'student',fullName:student.fullName});assert.equal(mapped.sender.displayName,'Mentor Name');assert.equal(mapped.message,'Mentor guidance')});
test('student cannot access another student conversation',async()=>{const repo=supportRepository as unknown as Record<string,unknown>;const original=repo.find;try{repo.find=async(_id:string,actor:{id:string})=>actor.id===student.id?conversation:null;await assert.rejects(supportService.get(conversation.id,other),/not found/)}finally{repo.find=original}});
test('message validation rejects blank, oversized, and closed conversations',async()=>{const repo=supportRepository as unknown as Record<string,unknown>;const original=repo.find;try{repo.find=async()=>conversation;await assert.rejects(supportService.send(conversation.id,{message:'   '},student),/message/);await assert.rejects(supportService.send(conversation.id,{message:'x'.repeat(2001)},student),/message/);repo.find=async()=>({...conversation,status:'closed'});await assert.rejects(supportService.send(conversation.id,{message:'hello'},student),error=>Boolean(error&&typeof error==='object'&&'code'in error&&error.code==='SUPPORT_CONVERSATION_CLOSED'))}finally{repo.find=original}});
test('assigned mentor can join while unrelated mentor is denied',async()=>{const repo=supportRepository as unknown as Record<string,unknown>;const original=repo.find;try{repo.find=async(_id:string,actor:{id:string})=>actor.id===mentor.id?{...conversation,mentorUserId:mentor.id}:null;assert.equal((await supportService.join(conversation.id,mentor)).mentorUserId,mentor.id);await assert.rejects(supportService.join(conversation.id,user('mentor','10000000-0000-4000-8000-000000000004')),/not found/)}finally{repo.find=original}});
test('mentor reply persists, appears in REST history, and links the canonical request',async()=>{const repo=supportRepository as unknown as Record<string,unknown>,notifications=notificationService as unknown as Record<string,unknown>;const keys=['find','addMessage','participants','messages'],originals=Object.fromEntries(keys.map(key=>[key,repo[key]])),originalCreate=notifications.create;const order:string[]=[],created:Array<Record<string,unknown>>=[];const persisted={id:'40000000-0000-4000-8000-000000000001',conversation_id:conversation.id,sender_role:'mentor',message:'A persisted reply',created_at:new Date(),inserted:true};try{repo.find=async()=>({...conversation,mentorUserId:mentor.id});repo.addMessage=async()=>{order.push('persist');return persisted};repo.participants=async()=>({student_user_id:student.id,mentor_user_id:mentor.id});repo.messages=async()=>[{id:persisted.id,conversationId:conversation.id,sender:{role:'mentor',displayName:'CampusCare Mentor'},message:persisted.message,createdAt:persisted.created_at}];notifications.create=async(input:Record<string,unknown>)=>{order.push('notify');created.push(input);return{}};await supportService.send(conversation.id,{message:persisted.message},mentor);assert.deepEqual(order,['persist','notify']);assert.equal(created[0].userId,student.id);assert.notEqual(created[0].userId,other.id);assert.equal(created[0].link,`/silent-help?request=${conversation.helpRequestId}`);const history=await supportService.get(conversation.id,student);assert.equal(history.messages[0].message,persisted.message)}finally{Object.assign(repo,originals);notifications.create=originalCreate}});
test('replayed support message creates no duplicate notification',async()=>{const repo=supportRepository as unknown as Record<string,unknown>,notifications=notificationService as unknown as Record<string,unknown>;const keys=['find','addMessage','participants'],originals=Object.fromEntries(keys.map(key=>[key,repo[key]])),originalCreate=notifications.create;let count=0;const replayMentor=user('mentor','10000000-0000-4000-8000-000000000005');try{repo.find=async()=>({...conversation,mentorUserId:replayMentor.id});repo.addMessage=async()=>({id:'4',conversation_id:conversation.id,sender_role:'mentor',message:'Already saved',created_at:new Date(),inserted:false});repo.participants=async()=>({student_user_id:student.id,mentor_user_id:replayMentor.id});notifications.create=async()=>{count+=1;return{}};await supportService.send(conversation.id,{message:'Already saved',clientMessageId:'50000000-0000-4000-8000-000000000001'},replayMentor);assert.equal(count,0)}finally{Object.assign(repo,originals);notifications.create=originalCreate}});
test('admin cannot list private support conversations',async()=>{const admin:PublicUser={...mentor,role:'admin'};await assert.rejects(Promise.resolve().then(()=>supportService.list(admin)),/students and mentors/)});
