import { queryDatabase } from '../../config/database.js';
import type { AiAnswer, AiMode } from './ai.types.js';
type Row = Record<string, unknown>;

export const aiRepository = {
  createConversation: async (userId:string,title:string,mode:AiMode) => (await queryDatabase<Row>('INSERT INTO ai_conversations(user_id,title,mode) VALUES($1,$2,$3) RETURNING id,title,mode,created_at,updated_at,archived_at',[userId,title,mode])).rows[0],
  findEmptyConversation: async (userId:string) => (await queryDatabase<Row>(`SELECT c.id,c.title,c.mode,c.created_at,c.updated_at FROM ai_conversations c WHERE c.user_id=$1 AND c.archived_at IS NULL AND NOT EXISTS(SELECT 1 FROM ai_messages m WHERE m.conversation_id=c.id) ORDER BY c.created_at DESC LIMIT 1`,[userId])).rows[0]??null,
  listConversations: async (userId:string) => (await queryDatabase<Row>(`SELECT c.id,c.title,c.mode,c.created_at,c.updated_at,(SELECT COUNT(*)::int FROM ai_messages m WHERE m.conversation_id=c.id) message_count FROM ai_conversations c WHERE c.user_id=$1 AND c.archived_at IS NULL ORDER BY c.updated_at DESC LIMIT 50`,[userId])).rows,
  findOwned: async (id:string,userId:string) => (await queryDatabase<Row>('SELECT id,title,mode,created_at,updated_at,archived_at FROM ai_conversations WHERE id=$1 AND user_id=$2',[id,userId])).rows[0] ?? null,
  messages: async (id:string) => (await queryDatabase<Row>(`SELECT id,role,content,structured_content,created_at FROM ai_messages WHERE conversation_id=$1 ORDER BY created_at ASC LIMIT 100`,[id])).rows,
  history: async (id:string) => (await queryDatabase<Row>(`SELECT role,content FROM ai_messages WHERE conversation_id=$1 ORDER BY created_at DESC LIMIT 8`,[id])).rows.reverse() as Array<{role:'student'|'assistant';content:string}>,
  lastMessage: async (id:string) => (await queryDatabase<Row>('SELECT role,content FROM ai_messages WHERE conversation_id=$1 ORDER BY created_at DESC LIMIT 1',[id])).rows[0]??null,
  addStudentMessage: async (id:string,content:string,safety:string) => queryDatabase('INSERT INTO ai_messages(conversation_id,role,content,safety_status) VALUES($1,\'student\',$2,$3)',[id,content,safety]),
  addAssistantMessage: async (id:string,result:AiAnswer,meta:{responseId?:string;inputTokens:number;outputTokens:number;duration:number;safety:string}) => queryDatabase('INSERT INTO ai_messages(conversation_id,role,content,structured_content,input_tokens,output_tokens,provider_response_id,safety_status,response_duration_ms) VALUES($1,\'assistant\',$2,$3,$4,$5,$6,$7,$8)',[id,result.answer,result,meta.inputTokens,meta.outputTokens,meta.responseId??null,meta.safety,meta.duration]),
  touch: (id:string) => queryDatabase('UPDATE ai_conversations SET updated_at=NOW() WHERE id=$1',[id]),
  setModeAndTitle: (id:string,mode:AiMode,title?:string) => queryDatabase('UPDATE ai_conversations SET mode=$2,title=COALESCE($3,title),updated_at=NOW() WHERE id=$1',[id,mode,title??null]),
  updateConversation: async (id:string,userId:string,title?:string,archived?:boolean) => (await queryDatabase<Row>(`UPDATE ai_conversations SET title=COALESCE($3,title),archived_at=CASE WHEN $4::boolean IS NULL THEN archived_at WHEN $4 THEN NOW() ELSE NULL END WHERE id=$1 AND user_id=$2 RETURNING id,title,mode,created_at,updated_at,archived_at`,[id,userId,title??null,archived??null])).rows[0]??null,
  archive: async (id:string,userId:string) => (await queryDatabase('UPDATE ai_conversations SET archived_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING id',[id,userId])).rowCount === 1,
  reserveDaily: async (userId:string,limit:number) => (await queryDatabase<Row>(`INSERT INTO ai_usage_daily(user_id,usage_date,request_count) VALUES($1,CURRENT_DATE,1) ON CONFLICT(user_id,usage_date) DO UPDATE SET request_count=ai_usage_daily.request_count+1,updated_at=NOW() WHERE ai_usage_daily.request_count < $2 RETURNING request_count`,[userId,limit])).rows[0] ?? null,
  recordUsage: (userId:string,ok:boolean,input:number,output:number,duration:number) => queryDatabase(`UPDATE ai_usage_daily SET successful_requests=successful_requests+$2,failed_requests=failed_requests+$3,input_tokens=input_tokens+$4,output_tokens=output_tokens+$5,total_duration_ms=total_duration_ms+$6,updated_at=NOW() WHERE user_id=$1 AND usage_date=CURRENT_DATE`,[userId,ok?1:0,ok?0:1,input,output,duration]),
  aggregateUsage: async (start:Date,end:Date) => (await queryDatabase<Row>(`SELECT COALESCE(SUM(request_count),0)::int total_requests,COUNT(DISTINCT user_id)::int active_ai_users,COALESCE(SUM(successful_requests),0)::int successful_requests,COALESCE(SUM(failed_requests),0)::int failed_requests,CASE WHEN SUM(successful_requests)>0 THEN ROUND(SUM(total_duration_ms)::numeric/SUM(successful_requests),0)::int ELSE 0 END average_response_ms FROM ai_usage_daily WHERE usage_date >= $1::date AND usage_date < $2::date`,[start,end])).rows[0],
  dailyUsage: async (start:Date,end:Date) => (await queryDatabase<Row>('SELECT usage_date::text date,request_count::int value FROM ai_usage_daily WHERE usage_date >= $1::date AND usage_date < $2::date ORDER BY usage_date',[start,end])).rows,
  modeUsage: async (start:Date,end:Date) => (await queryDatabase<Row>('SELECT mode label,COUNT(*)::int value FROM ai_conversations WHERE created_at >= $1 AND created_at < $2 GROUP BY mode ORDER BY value DESC',[start,end])).rows
  ,studentUsage: async (userId:string,start:Date,end:Date) => (await queryDatabase<Row>(`SELECT COUNT(*)::int sessions,(SELECT mode FROM ai_conversations WHERE user_id=$1 AND created_at >= $2 AND created_at < $3 GROUP BY mode ORDER BY COUNT(*) DESC LIMIT 1) most_used_mode,MAX(updated_at) last_session FROM ai_conversations WHERE user_id=$1 AND created_at >= $2 AND created_at < $3`,[userId,start,end])).rows[0]
};
