import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { PageHeader } from '../components/common/PageHeader';
import { getApiErrorCode, getApiErrorMessage } from '../services/apiClient';
import { aiService } from '../services/aiService';
import type { AiAnswer, AiConversation, AiMessage, AiMode } from '../types/ai';

const modes: Array<{ value: AiMode; label: string }> = [
  { value: 'question', label: 'Ask a Question' }, { value: 'explain', label: 'Explain a Concept' },
  { value: 'study-plan', label: 'Create a Study Plan' }, { value: 'summarize', label: 'Summarize Notes' },
  { value: 'practice', label: 'Generate Practice Questions' }, { value: 'code-help', label: 'Explain Code' },
  { value: 'revision', label: 'Revision Checklist' }
];
const suggestions = ['Explain database normalization with a simple example.','Create a 7-day study plan for operating systems.','Generate five practice questions about SQL joins.','Explain this C# code step by step.','Create a revision checklist for my exam.'];
const liveProviderEnabled = import.meta.env.VITE_AI_PROVIDER_ENABLED === 'true';
const unavailableCodes = new Set(['AI_ASSISTANT_UNAVAILABLE','AI_PROVIDER_QUOTA_UNAVAILABLE','AI_PROVIDER_CONFIGURATION_ERROR','AI_PROVIDER_UNAVAILABLE']);

export default function AIStudyAssistantPage() {
  const [items,setItems]=useState<AiConversation[]>([]), [active,setActive]=useState<AiConversation|null>(null), [messages,setMessages]=useState<AiMessage[]>([]);
  const [mode,setMode]=useState<AiMode>('question'), [input,setInput]=useState(''), [error,setError]=useState(''), [loading,setLoading]=useState(true), [sending,setSending]=useState(false);
  const [remaining,setRemaining]=useState<number|null>(null), [retryText,setRetryText]=useState<string|null>(null), [historyOpen,setHistoryOpen]=useState(false);
  const [providerUnavailable,setProviderUnavailable]=useState(!liveProviderEnabled);
  const controller=useRef<AbortController|null>(null), textarea=useRef<HTMLTextAreaElement|null>(null);
  const limitReached=remaining===0;
  const loadList=async()=>{const list=await aiService.list();setItems(list);return list};
  useEffect(()=>{loadList().catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false))},[]);

  const open=async(c:AiConversation)=>{try{setError('');const data=await aiService.get(c.id);setActive(data.conversation);setMode(data.conversation.mode);setMessages(data.messages);setHistoryOpen(false)}catch(e){setError(getApiErrorMessage(e))}};
  const create=async()=>{try{setError('');const c=await aiService.create({title:'New study session',mode});setItems(v=>v.some(x=>x.id===c.id)?v:[c,...v]);setActive(c);setMode(c.mode);setMessages([]);setHistoryOpen(false);textarea.current?.focus()}catch(e){setError(getApiErrorMessage(e))}};
  const rename=async()=>{if(!active)return;const title=window.prompt('Conversation title',active.title)?.trim();if(!title)return;try{const updated=await aiService.update(active.id,{title});setActive(updated);await loadList()}catch(e){setError(getApiErrorMessage(e))}};
  const refreshActive=async(id:string)=>{const data=await aiService.get(id);setActive(data.conversation);setMode(data.conversation.mode);setMessages(data.messages);await loadList()};
  const send=async(textOverride?:string)=>{const text=(textOverride??input).trim();if(!text||sending||limitReached||providerUnavailable)return;let conversation=active;try{setSending(true);setError('');setRetryText(null);if(!conversation){conversation=await aiService.create({title:'New study session',mode});setActive(conversation);setItems(v=>v.some(x=>x.id===conversation!.id)?v:[conversation!,...v])}if(!textOverride)setInput('');setMessages(v=>v.some(m=>m.role==='student'&&m.content===text&&m.id.startsWith('local-'))?v:[...v,{id:`local-${Date.now()}`,role:'student',content:text,created_at:new Date().toISOString()}]);controller.current=new AbortController();const result=await aiService.send(conversation.id,text,mode,controller.current.signal);setProviderUnavailable(false);setRemaining(result.remainingToday);setMessages(v=>[...v.filter(m=>!m.id.startsWith('local-')),{id:`assistant-${Date.now()}`,role:'assistant',content:result.message?.answer??'',structured_content:result.message,created_at:new Date().toISOString()}]);await refreshActive(conversation.id)}catch(e){const unavailable=unavailableCodes.has(getApiErrorCode(e)??'');setProviderUnavailable(unavailable);setError(unavailable?'':getApiErrorMessage(e));setRetryText(unavailable?null:text);setInput(text);if(conversation)await refreshActive(conversation.id).catch(()=>undefined)}finally{setSending(false);controller.current=null;if(!providerUnavailable)textarea.current?.focus()}};
  const selectSuggestion=(text:string)=>{setInput(text);setRetryText(null);requestAnimationFrame(()=>textarea.current?.focus())};
  const onKeyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}};
  const archive=async()=>{if(!active||!window.confirm('Archive this private study conversation?'))return;await aiService.archive(active.id);setActive(null);setMessages([]);await loadList()};

  return <div className="space-y-5 overflow-x-hidden"><PageHeader eyebrow="Student workspace" title="AI Study Assistant" status={providerUnavailable?'AI service unavailable':undefined} description={providerUnavailable?'Review the implemented study modes and your saved study sessions.':'Choose a mode, select a shortcut or type your own message, then edit before sending.'}/>
    {providerUnavailable?<section className="ai-demo-notice" role="status"><span className="ai-demo-icon" aria-hidden="true">i</span><div><h2>AI Study Assistant – Demo Mode</h2><p>Live AI responses are currently disabled because this deployment does not have an active AI provider configured.</p><small>The assistant architecture and study modes are implemented and can be enabled when a provider is configured.</small></div></section>:null}
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><strong>Privacy and accuracy notice:</strong> Do not share passwords, identification details, confidential academic records, or highly sensitive personal information. Conversations are saved privately. Verify AI responses.</div>
    {error?<div className="alert-error flex items-center justify-between gap-3"><span>{error}</span>{retryText?<button className="font-bold underline" onClick={()=>void send(retryText)}>Retry</button>:null}</div>:null}
    <button className="btn-secondary lg:hidden" onClick={()=>setHistoryOpen(v=>!v)}>{historyOpen?'Hide':'Show'} conversation history</button>
    <div className="grid min-h-[620px] gap-4 lg:grid-cols-[250px_minmax(0,1fr)]">
      <aside className={`panel ${historyOpen?'block':'hidden'} lg:block`}><button className="btn-primary w-full" disabled={providerUnavailable} onClick={()=>void create()}>New conversation</button><div className="mt-4 space-y-2">{loading?<p className="empty-text">Loading history…</p>:items.length?items.map(c=><button key={c.id} onClick={()=>void open(c)} className={`w-full rounded-xl border p-3 text-left text-sm ${active?.id===c.id?'border-teal-300 bg-teal-50':'border-slate-200 bg-white'}`}><strong className="block truncate">{c.title}</strong><span className="mt-1 block text-xs capitalize text-slate-500">{c.mode.replace(/-/g,' ')}</span></button>):<p className="empty-state">No study sessions yet.</p>}</div></aside>
      <section className="panel flex min-w-0 flex-col pb-24 lg:pb-5"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-4"><div><h2 className="font-bold">{active?.title??'Start a study session'}</h2><p className="text-xs text-slate-500">Suggested prompts are optional shortcuts.</p></div>{active?<div className="flex gap-2"><button className="btn-secondary min-h-9 px-3 py-1 text-xs" onClick={()=>void rename()}>Rename</button><button className="btn-secondary min-h-9 px-3 py-1 text-xs" onClick={()=>void archive()}>Archive</button></div>:null}</div>
        <div className="my-3 flex-1 space-y-3 overflow-y-auto"><label className="field-label" htmlFor="ai-mode">Assistant mode</label><select id="ai-mode" className="input max-w-sm" value={mode} onChange={e=>setMode(e.target.value as AiMode)} disabled={sending}>{modes.map(m=><option key={m.value} value={m.value}>{m.label}</option>)}</select>
          {!messages.length?<div><p className="mb-2 text-xs font-bold text-slate-600">Optional prompt shortcuts</p><div className="grid gap-2 sm:grid-cols-2">{suggestions.map(s=><button key={s} disabled={providerUnavailable} className="panel-soft text-left text-xs leading-5 disabled:cursor-not-allowed disabled:opacity-55" onClick={()=>selectSuggestion(s)}>{s}</button>)}</div></div>:messages.map(m=><Message key={m.id} message={m}/>)}{sending?<div className="rounded-xl bg-teal-50 p-3 text-sm text-teal-800">Preparing study guidance…</div>:null}</div>
        <div className="border-t border-slate-100 bg-white pt-3"><div className="mb-1.5 flex flex-wrap items-center justify-between gap-2"><label className="field-label !mb-0" htmlFor="ai-message">Your custom message</label>{providerUnavailable?<span className="ai-provider-label">AI provider unavailable</span>:null}</div><textarea id="ai-message" ref={textarea} className="textarea min-h-24 w-full" value={input} maxLength={6000} disabled={providerUnavailable} onKeyDown={onKeyDown} onChange={e=>setInput(e.target.value)} placeholder={providerUnavailable?'Live AI responses are disabled in this demo.':'Type any study question here… Enter sends; Shift+Enter adds a line.'}/><div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>{input.length}/6000 {remaining!==null?`• ${remaining} requests remaining today`:''}</span><div className="flex gap-2"><button className="btn-secondary" disabled={!input||sending||providerUnavailable} onClick={()=>setInput('')}>Clear</button>{sending?<button className="btn-secondary" onClick={()=>controller.current?.abort()}>Cancel</button>:null}<button className="btn-primary" disabled={!input.trim()||sending||limitReached||providerUnavailable} onClick={()=>void send()}>Send</button></div></div></div>
      </section></div></div>;
}

function Message({message}:{message:AiMessage}){const a=message.structured_content as AiAnswer|undefined;return <article className={`max-w-full rounded-2xl p-4 ${message.role==='student'?'ml-auto sm:max-w-[85%] bg-[#0b1d35] text-white':'mr-auto sm:max-w-[92%] border border-teal-100 bg-teal-50 text-slate-800'}`}><p className="mb-2 text-[10px] font-extrabold uppercase tracking-wider opacity-60">{message.role==='student'?'Student':'CampusCare AI Study Assistant'}</p><p className="whitespace-pre-wrap break-words text-sm leading-6">{a?.answer??message.content}</p>{a?.keyPoints?.length?<div className="mt-3"><strong className="text-xs">Key points</strong><ul className="mt-1 list-disc space-y-1 pl-5 text-sm">{a.keyPoints.map(x=><li key={x}>{x}</li>)}</ul></div>:null}{a?.nextSteps?.length?<div className="mt-3"><strong className="text-xs">Next steps</strong><ul className="mt-1 list-disc space-y-1 pl-5 text-sm">{a.nextSteps.map(x=><li key={x}>{x}</li>)}</ul></div>:null}{message.role==='assistant'?<button className="mt-3 text-xs font-bold text-teal-800" onClick={()=>void navigator.clipboard.writeText(a?.answer??message.content)}>Copy answer</button>:null}</article>}
