import { useEffect, useState } from 'react';
import { getApiErrorMessage } from '../services/apiClient';
import { securityService, type AuditItem } from '../services/securityService';

export default function AuditLogsPage() {
  const [items,setItems]=useState<AuditItem[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[action,setAction]=useState(''),[role,setRole]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[error,setError]=useState('');
  useEffect(()=>{const params:Record<string,string|number>={page,limit:20};if(action)params.action=action;if(role)params.role=role;if(start)params.start=start;if(end)params.end=end;void securityService.auditLogs(params).then(data=>{setItems(data.items);setTotal(data.total);setError('')}).catch(err=>setError(getApiErrorMessage(err)))},[action,role,start,end,page]);
  return <div className="space-y-5"><header><p className="text-xs font-extrabold uppercase tracking-widest text-teal-700">Security & accountability</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Audit Logs</h1><p className="mt-2 text-sm text-slate-600">Meaningful platform actions without private message content or credentials.</p></header><section className="premium-card p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder="Filter exact action" value={action} onChange={e=>{setPage(1);setAction(e.target.value)}}/><select className="input" value={role} onChange={e=>{setPage(1);setRole(e.target.value)}}><option value="">All roles</option><option value="student">Student</option><option value="mentor">Mentor</option><option value="admin">Admin</option></select><input aria-label="Start date" className="input" type="date" value={start} onChange={e=>{setPage(1);setStart(e.target.value)}}/><input aria-label="End date" className="input" type="date" value={end} onChange={e=>{setPage(1);setEnd(e.target.value)}}/></div></section>{error?<div className="alert-error">{error}</div>:null}<section className="premium-card overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Timestamp','Actor','Role','Action','Entity','Context'].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{items.map(item=><tr className="border-t border-slate-100" key={item.id}><td className="whitespace-nowrap px-4 py-3">{new Date(item.timestamp).toLocaleString()}</td><td className="px-4 py-3">{item.actor}</td><td className="px-4 py-3 capitalize">{item.role??'—'}</td><td className="px-4 py-3 font-semibold">{item.action}</td><td className="px-4 py-3">{item.entity??'—'}</td><td className="px-4 py-3 text-xs text-slate-500">{item.context ? Object.entries(item.context).map(([k,v])=>`${k}: ${String(v)}`).join(', ') : '—'}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-4 md:hidden">{items.map(item=><article className="rounded-xl border border-slate-200 p-3" key={item.id}><strong className="text-sm">{item.action}</strong><p className="mt-1 text-xs text-slate-500">{item.actor} · {item.role??'system'} · {new Date(item.timestamp).toLocaleString()}</p><p className="mt-2 text-xs text-slate-600">{item.entity??'Platform activity'}</p></article>)}</div>{!items.length?<p className="p-8 text-center text-sm text-slate-500">No audit activity matches these filters.</p>:null}<div className="flex items-center justify-between border-t p-4 text-sm"><span>{total} records</span><div className="flex gap-2"><button className="btn-secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="btn-secondary" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></section></div>;
}
