import assert from'node:assert/strict';import test from'node:test';import{authenticateRealtimeToken,createSupportRealtimeHandlers}from'./realtime.server.js';import{tokenUtils}from'../utils/token.js';import{supportService}from'../modules/support/support.service.js';import{AppError}from'../utils/httpError.js';
test('realtime authentication rejects missing and invalid JWTs',async()=>{await assert.rejects(authenticateRealtimeToken(undefined),error=>Boolean(error&&typeof error==='object'&&'data'in error));await assert.rejects(authenticateRealtimeToken('invalid-token'))});
test('realtime authentication derives identity from verified JWT',async()=>{const token=tokenUtils.sign({userId:'10000000-0000-4000-8000-000000000001',role:'student'});const result=await authenticateRealtimeToken(token,async id=>({id,role:'student',fullName:'Student',email:'student@example.com',createdAt:new Date(),updatedAt:new Date()}));assert.equal(result.id,'10000000-0000-4000-8000-000000000001');assert.equal(result.role,'student')});
test('all support handlers tolerate missing acknowledgements and contain failures',async()=>{const service=supportService as unknown as Record<string,unknown>;const keys=['join','send','markRead','authorize'];const originals=Object.fromEntries(keys.map(key=>[key,service[key]]));const joined:string[]=[],left:string[]=[],emitted:string[]=[];const socket={join:async(room:string)=>{joined.push(room)},leave:async(room:string)=>{left.push(room)},to:()=>({emit:(event:string)=>{emitted.push(event)}})};const user={id:'10000000-0000-4000-8000-000000000001',role:'student' as const,fullName:'Student',email:'student@example.com',createdAt:new Date(),updatedAt:new Date()};const id='20000000-0000-4000-8000-000000000001';try{service.join=async(value:string)=>{if(value==='20000000-0000-4000-8000-000000000099')throw new AppError(404,'Not found',[],'SUPPORT_CONVERSATION_NOT_FOUND');return{id:value}};service.send=async()=>{throw new Error('contained rejection')};service.markRead=async()=>({read:true});service.authorize=async()=>({conversation:{id}});const handlers=createSupportRealtimeHandlers(socket,user);
await assert.doesNotReject(handlers.join({conversationId:id}));assert.deepEqual(joined,[`support:${id}`]);let joinedAck:unknown;await handlers.join({conversationId:id},(result:unknown)=>{joinedAck=result});assert.equal((joinedAck as{ok:boolean}).ok,true);
await assert.doesNotReject(handlers.join({conversationId:'bad'}));let malformed:unknown;await handlers.join({},(result:unknown)=>{malformed=result});assert.deepEqual(malformed,{ok:false,code:'REALTIME_INVALID_PAYLOAD',message:'A valid conversation ID is required.'});
let unauthorized:unknown;await handlers.join({conversationId:'20000000-0000-4000-8000-000000000099'},(result:unknown)=>{unauthorized=result});assert.equal((unauthorized as{code:string}).code,'SUPPORT_CONVERSATION_NOT_FOUND');
await assert.doesNotReject(handlers.leave({conversationId:id}));assert.deepEqual(left,[`support:${id}`]);await assert.doesNotReject(handlers.typing({conversationId:id,active:true}));assert.deepEqual(emitted,['support:typing']);await assert.doesNotReject(handlers.typingStop({conversationId:id}));await assert.doesNotReject(handlers.read({conversationId:id}));await assert.doesNotReject(handlers.message({conversationId:id,message:'hello'}));
let rejected:unknown;await handlers.message({conversationId:id,message:'hello'},(result:unknown)=>{rejected=result});assert.equal((rejected as{ok:boolean}).ok,false)}finally{Object.assign(service,originals)}});
